"""Create tables

Revision ID: 49052717c106
Revises: 
Create Date: 2025-06-03 13:00:23.365132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49052717c106"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "law",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "selectielijsten",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("selectielijsten", sa.String(), nullable=True),
        sa.Column("procescategorie", sa.String(), nullable=True),
        sa.Column("process_number", sa.String(), nullable=True),
        sa.Column("process_description", sa.String(), nullable=True),
        sa.Column("waardering", sa.String(), nullable=True),
        sa.Column("toelichting", sa.String(), nullable=True),
        sa.Column("voorbeelden", sa.String(), nullable=True),
        sa.Column("voorbeelden_werkdoc_bsd", sa.String(), nullable=True),
        sa.Column("persoonsgegevens_aanwezig", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("selectielijsten")
    op.drop_table("law")
    op.drop_table("chat_message")
    # ### end Alembic commands ###
