"""empty message

Revision ID: 5a6be4fcc3bc
Revises: 49052717c106
Create Date: 2025-07-02 15:21:26.989527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6be4fcc3bc'
down_revision: Union[str, None] = '49052717c106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selectielijsten', sa.Column('proces_komt_voor_bij', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selectielijsten', 'proces_komt_voor_bij')
    # ### end Alembic commands ###
